source 'git@git.postindustria.com:mobile-components.git'
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '7.0'

pod 'XHTransformation/Base', :path => '../'

target 'XHCLScraping' do
    pod 'XHTransformation'
end
