source 'git@git.postindustria.com:mobile-components.git'
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '7.0'

pod 'SkyScraper/Base', :path => '../'

target 'CLSkyScraper' do
    pod 'SkyScraper'
    pod 'SVProgressHUD'
end
